apiVersion: v1
kind: Service
metadata:
  name: content-service
spec:
  selector:
    app: content-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 11080
  type: ClusterIP
